#pragma once

static const char control_page[] =
"<!doctype html><html lang='zh-CN'><meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>空调温控</title><style>"
"body{font:16px system-ui;margin:0;background:#f3f6f8;color:#16324a}"
"main{max-width:560px;margin:auto;padding:20px}h1{font-size:25px}"
"section{background:white;border-radius:14px;padding:18px;margin:16px 0;box-shadow:0 2px 10px #0001}"
"label{display:block;margin:12px 0}input,select,button{font:inherit;padding:9px;border-radius:8px;border:1px solid #aab8c1}"
"input[type=number]{width:90px}button{background:#007da5;color:white;border:0;margin:4px 5px 4px 0}"
"button{box-shadow:0 3px 0 #005b78;transition:background .1s,transform .1s,box-shadow .1s}"
"button:not(:disabled):active{background:#005b78;transform:translateY(2px);box-shadow:0 1px 0 #00465d}"
"button:disabled{opacity:.5}.note{font-size:13px;color:#526b78}#message{min-height:24px;color:#a33822}"
"</style><main><h1>空调温控</h1><section><div id='temperature'>温度读取中…</div>"
"<div id='battery'>电池电压读取中…</div>"
"<div class='note'>热点未使用3分钟关闭，使用后空闲10分钟关闭；S1重新开启，S2暂停温控。</div></section>"
"<section><label>红外发送频率 <select id='carrier' onchange='saveCarrier()' disabled>"
"<option value='36'>36</option><option value='38' selected>38</option><option value='40'>40</option>"
"</select> kHz</label><div class='note'>两组共用；修改后已学习的红外码也按此频率发送。</div></section>"
"<div id='cards'></div><p id='message'></p>"
"<p class='note'>未自动弹出时，请访问 http://192.168.4.1 。红外学习时保持手机连接，按一次遥控器目标按键。</p></main>"
"<script>"
"const cards=document.getElementById('cards'),msg=document.getElementById('message');"
"for(let i=1;i<=2;i++)cards.innerHTML+=`<section><h2>规则 ${i}</h2>"
"<label>触发温度 <input id='t${i}' type='number' min='-10' max='50' step='0.1'> °C</label>"
"<label>方向 <select id='d${i}'><option value='1'>升至</option><option value='0'>降至</option></select></label>"
"<label><input id='e${i}' type='checkbox'> 启用</label>"
"<button onclick='save(${i})'>保存规则</button><button onclick='learn(${i})'>学习红外</button>"
"<button onclick='send(${i})'>测试发送</button><div id='info${i}' class='note'></div></section>`;"
"async function api(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});"
"const j=await r.json();if(!r.ok)throw Error(j.error||('HTTP '+r.status));return j}"
"let savedCarrier=38;async function saveCarrier(){const sel=document.getElementById('carrier');"
"const khz=Number(sel.value);sel.disabled=true;try{await api('/api/carrier',{carrier:khz});"
"savedCarrier=khz;msg.textContent='红外发送频率已保存'}catch(e){sel.value=String(savedCarrier);"
"msg.textContent='频率保存失败：'+e.message}finally{sel.disabled=false}}"
"async function save(i){try{const value=document.getElementById('t'+i).value;const t=Number(value);"
"if(value.trim()===''||!Number.isFinite(t))throw Error('请输入温度');await api('/api/rule',{slot:i,threshold10:Math.round(t*10),"
"rising:document.getElementById('d'+i).value==='1',enabled:document.getElementById('e'+i).checked});"
"msg.textContent='规则已保存';refresh()}catch(e){msg.textContent=e.message}}"
"async function learn(i){try{await api('/api/learn',{slot:i});"
"msg.textContent='请在15秒内按一次遥控器目标按键';refresh()}catch(e){msg.textContent=e.message}}"
"async function send(i){try{await api('/api/send',{slot:i});msg.textContent='已发送第'+i+'组红外码';refresh()}"
"catch(e){msg.textContent=e.message}}"
"let loaded=false,lastLearn=-1;async function refresh(){try{const r=await fetch('/api/status',{cache:'no-store'});"
"if(!r.ok)throw Error('状态读取失败');const s=await r.json();"
"document.getElementById('temperature').textContent=s.valid?('当前温度 '+(s.temperature10/10).toFixed(1)+' °C')"
":('温度读取失败，错误码 '+s.sensorError);"
"document.getElementById('battery').textContent=s.batteryValid?('电池电压 '+(s.batteryMv/1000).toFixed(2)+' V')"
":('电池电压读取失败，错误码 '+s.batteryError);"
"if(!loaded){const sel=document.getElementById('carrier');savedCarrier=s.carrier;"
"sel.value=String(savedCarrier);sel.disabled=false}"
"for(let i=1;i<=2;i++){const q=s.rules[i-1];if(!loaded){document.getElementById('t'+i).value=(q.threshold10/10).toFixed(1);"
"document.getElementById('d'+i).value=q.rising?'1':'0';document.getElementById('e'+i).checked=q.enabled}"
"document.getElementById('info'+i).textContent=(q.learned?'已学习':'未学习')+"
"(q.sendError?'；上次发送错误码 '+q.sendError:'')}loaded=true;"
"if(s.learnState!==lastLearn){lastLearn=s.learnState;if(s.learnState===3)msg.textContent='红外学习成功并已保存';"
"if(s.learnState===4)msg.textContent='红外学习失败，错误码 '+s.learnError}}"
"catch(e){msg.textContent=e.message}}refresh();setInterval(refresh,2000);"
"</script></html>";
