#pragma once

/* 控制页由相邻 C 字符串拼接；说明放在字符串外，避免改变实际发送的 HTML。 */
static const char control_page[] =
"<!doctype html><html lang='zh-CN'><meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>空调温控</title><style>"
"body{font:16px system-ui;margin:0;background:#f3f6f8;color:#16324a}"
"main{max-width:560px;margin:auto;padding:20px}h1{font-size:25px}"
"section{background:white;border-radius:14px;padding:18px;margin:16px 0;box-shadow:0 2px 10px #0001}"
"label{display:block;margin:12px 0}input,select,button{font:inherit;padding:9px;border-radius:8px;border:1px solid #aab8c1}"
"input[type=number]{width:90px}button{background:#007da5;color:white;border:0;margin:4px 5px 4px 0}"
"button{box-shadow:0 3px 0 #005b78;transition:background .1s,transform .1s,box-shadow .1s}"
"button:not(:disabled):active{background:#005b78;transform:translateY(2px);box-shadow:0 1px 0 #00465d}"
"button:disabled{opacity:.5}.note{font-size:13px;color:#526b78}#message{min-height:24px;color:#a33822}"
"#lowBattery{color:#a33822;font-weight:600}"
"h2{touch-action:manipulation;user-select:none}"
".modal{position:fixed;inset:0;background:#0006;display:flex;align-items:center;justify-content:center;padding:20px;z-index:10}"
".modal[hidden]{display:none}.modal section{box-sizing:border-box;width:100%;max-width:340px;max-height:100%;overflow-y:auto;margin:0}"
"#calError{color:#a33822;min-height:24px}"
"</style><main><h1>空调温控</h1><section><div id='temperature'>温度读取中…</div>"
"<div id='battery'>电池电压读取中…</div>"
"<div id='lowBattery' role='status' hidden>低电量：电池电压低于3.5 V，请及时充电。</div>"
"<div class='note'>热点未使用3分钟关闭，使用后空闲10分钟关闭；休眠中两键都可唤醒，S1开关Wi-Fi热点，S2关闭热点进入休眠，每60秒测温并按规则发送红外。</div></section>"
"<p class='note'>热点开启时暂停自动温控，可手动测试红外；关闭后每60秒采温。首次满足规则即发送，后续按温度变化速度调整为2～10分钟间隔。</p>"
"<section><label>红外发送频率 <select id='carrier' onchange='saveCarrier()' disabled>"
"<option value='36'>36</option><option value='38' selected>38</option><option value='40'>40</option>"
"</select> kHz</label><div class='note'>两组共用；修改后已学习的红外码也按此频率发送。</div></section>"
"<div id='cards'></div><p id='message'></p>"
"<p class='note'>未自动弹出时，请访问 http://192.168.4.1 。红外学习时保持手机连接，按一次遥控器目标按键。</p></main>"
"<div id='calModal' class='modal' role='dialog' aria-modal='true' aria-labelledby='calTitle' hidden>"
"<section><h2 id='calTitle'></h2><p id='calCurrent'></p><form onsubmit='submitCalibration(event)'>"
"<label id='calLabel' for='calValue'></label><input id='calValue' type='number' required>"
"<p class='note'>输入参考仪表的当前实测值，保存后重启仍有效。</p>"
"<p id='calError' role='status'></p><button id='calSave' type='submit'>保存</button>"
"<button id='calCancel' type='button' onclick='closeCalibration()'>取消</button></form></section></div>"
"<script>"
/* 动态创建两组规则卡片；页面槽位从 1 开始，温度通过 API 使用 0.1 ℃整数。 */
"const cards=document.getElementById('cards'),msg=document.getElementById('message');"
"for(let i=1;i<=2;i++)cards.innerHTML+=`<section><h2 onclick='calibrationTap(${i})'>规则 ${i}</h2>"
"<label>触发温度 <input id='t${i}' type='number' min='-10' max='50' step='0.1'> °C</label>"
"<label>方向 <select id='d${i}'><option value='1'>升至</option><option value='0'>降至</option></select></label>"
"<label><input id='e${i}' type='checkbox'> 启用</label>"
"<button onclick='save(${i})'>保存规则</button><button id='learn${i}' onclick='learn(${i})'>学习红外</button>"
"<button onclick='send(${i})'>测试发送</button><div id='info${i}' class='note'></div></section>`;"
/* 统一处理 POST 和 HTTP 错误；后续调用在页面消息区显示失败原因。 */
"async function api(path,data){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});"
"const j=await r.json();if(!r.ok){const e=Error(j.error||('HTTP '+r.status));e.status=r.status;throw e}return j}"
/* 保存载波期间禁用选择框；失败恢复上次已保存值，避免显示未生效的设置。 */
"let savedCarrier=38;async function saveCarrier(){const sel=document.getElementById('carrier');"
"const khz=Number(sel.value);sel.disabled=true;try{await api('/api/carrier',{carrier:khz});"
"savedCarrier=khz;msg.textContent='红外发送频率已保存'}catch(e){sel.value=String(savedCarrier);"
"msg.textContent='频率保存失败：'+e.message}finally{sel.disabled=false}}"
"async function save(i){try{const value=document.getElementById('t'+i).value;const t=Number(value);"
"if(value.trim()===''||!Number.isFinite(t))throw Error('请输入温度');await api('/api/rule',{slot:i,threshold10:Math.round(t*10),"
"rising:document.getElementById('d'+i).value==='1',enabled:document.getElementById('e'+i).checked});"
"msg.textContent='规则已保存';refresh()}catch(e){msg.textContent=e.message}}"
"let learnSlot=0,learnPending=false,statusSeq=0,statusApplied=0;function updateLearnButtons(active){for(let i=1;i<=2;i++){const b=document.getElementById('learn'+i);"
"b.textContent=active&&(!learnSlot||learnSlot===i)?'学习中···':'学习红外';b.disabled=active}}"
"async function learn(i){if(learnPending||lastLearn===1||lastLearn===2)return;statusApplied=++statusSeq;learnSlot=i;learnPending=true;updateLearnButtons(true);"
"try{await api('/api/learn',{slot:i});statusApplied=++statusSeq;lastLearn=1;learnPending=false;msg.textContent='请在15秒内按一次遥控器目标按键';await refresh()}"
"catch(e){statusApplied=++statusSeq;learnPending=false;learnSlot=0;updateLearnButtons(false);msg.textContent=e.message}}"
"async function send(i){try{await api('/api/send',{slot:i});msg.textContent='已发送第'+i+'组红外码';refresh()}"
"catch(e){msg.textContent=e.message}}"
"let latestStatus=null,calType=0,calSaving=false,calReadyAt=0;const calClicks=[{count:0,start:0},{count:0,start:0}];"
"function resetCalClicks(){for(const c of calClicks)c.count=0}"
"function calibrationTap(i){if(calType||calSaving)return;const c=calClicks[i-1],now=Date.now();"
"if(!c.count||now-c.start>3000){c.count=0;c.start=now}if(++c.count<5)return;resetCalClicks();"
"const s=latestStatus;if(!s||(i===1?!s.valid:!s.batteryValid)){msg.textContent='当前读数不可用，请稍后重试';return}"
"calType=i;calReadyAt=now+800;const v=document.getElementById('calValue');"
"document.getElementById('calTitle').textContent=i===1?'温度校正':'电池电压校正';"
"document.getElementById('calLabel').textContent=i===1?'当前实测温度（°C）':'当前实测电压（V）';"
"document.getElementById('calCurrent').textContent=i===1?'设备当前温度 '+(s.temperature10/10).toFixed(1)+' °C'"
":'设备当前电压 '+(s.batteryMv/1000).toFixed(3)+' V';"
"v.min=i===1?'-10':'2.5';v.max=i===1?'50':'4.5';v.step=i===1?'0.1':'0.001';"
"v.value=i===1?(s.temperature10/10).toFixed(1):(s.batteryMv/1000).toFixed(3);"
"document.getElementById('calError').textContent='';document.getElementById('calModal').hidden=false}"
"function closeCalibration(saved=false){if(calSaving||(!saved&&Date.now()<calReadyAt))return;document.getElementById('calModal').hidden=true;calType=0;resetCalClicks()}"
"async function submitCalibration(event){event.preventDefault();if(calSaving||!calType||Date.now()<calReadyAt)return;"
"const text=document.getElementById('calValue').value.trim(),value=Number(text),scale=calType===1?10:1000;"
"const target=Math.round(value*scale),error=document.getElementById('calError');"
"if(!text||!Number.isFinite(value)||Math.abs(value*scale-target)>0.000001||"
"(calType===1?(target<-100||target>500):(target<2500||target>4500))){error.textContent='请输入范围内的实测值，并使用规定精度';return}"
"calSaving=true;const save=document.getElementById('calSave'),cancel=document.getElementById('calCancel'),input=document.getElementById('calValue');"
"save.disabled=cancel.disabled=input.disabled=true;let saved=false;try{"
"await api('/api/calibration',calType===1?{type:'temperature',reference10:target}:{type:'battery',referenceMv:target});"
"saved=true;msg.textContent='校准已保存'}catch(e){error.textContent=e.status===400?'参考值或校准幅度超出允许范围':"
"e.status===409?'当前读数不可用或已过期，请等待读数更新后重试':e.status>=500?'校准保存失败，请重试':'校准失败：'+e.message}"
"finally{calSaving=false;save.disabled=cancel.disabled=input.disabled=false}if(saved){closeCalibration(true);await refresh()}}"
/* 每 2 秒轮询状态；配置仅首次填入，避免覆盖用户正在编辑的规则。
 * 丢弃已失效或晚于新响应到达的旧响应；学习操作使此前请求失效。
 * 学习状态变化时更新提示，无效温度和电压显示对应错误。 */
"let loaded=false,lastLearn=-1;async function refresh(){const seq=++statusSeq;try{const r=await fetch('/api/status',{cache:'no-store'});"
"if(!r.ok)throw Error('状态读取失败');const s=await r.json();"
"if(seq<statusApplied){console.debug('Ignored stale status response',seq);return}statusApplied=seq;"
"latestStatus=s;"
"const learning=learnPending||s.learnState===1||s.learnState===2;updateLearnButtons(learning);if(!learning)learnSlot=0;"
"document.getElementById('temperature').textContent=s.valid?('当前温度 '+(s.temperature10/10).toFixed(1)+' °C')"
":('温度读取失败，错误码 '+s.sensorError);"
"document.getElementById('battery').textContent=s.batteryValid?('电池电压 '+(s.batteryMv/1000).toFixed(2)+' V')"
":('电池电压读取失败，错误码 '+s.batteryError);"
"document.getElementById('lowBattery').hidden=!(s.batteryValid&&s.batteryMv<3500);"
"if(!loaded){const sel=document.getElementById('carrier');savedCarrier=s.carrier;"
"sel.value=String(savedCarrier);sel.disabled=false}"
"for(let i=1;i<=2;i++){const q=s.rules[i-1];if(!loaded){document.getElementById('t'+i).value=(q.threshold10/10).toFixed(1);"
"document.getElementById('d'+i).value=q.rising?'1':'0';document.getElementById('e'+i).checked=q.enabled}"
"document.getElementById('info'+i).textContent=(q.learned?'已学习':'未学习')+"
"(q.sendError?'；上次发送错误码 '+q.sendError:'')}loaded=true;"
"if(s.learnState!==lastLearn){lastLearn=s.learnState;if(s.learnState===3)msg.textContent='红外学习成功并已保存';"
"if(s.learnState===4)msg.textContent='红外学习失败，错误码 '+s.learnError}}"
"catch(e){if(seq<statusApplied){console.debug('Ignored stale status error',seq);return}statusApplied=seq;latestStatus=null;msg.textContent=e.message}}refresh();setInterval(refresh,2000);"
"</script></html>";
