# Generate a local SDK override; never write to the installed SDK.
file(TO_CMAKE_PATH "$ENV{IDF_PATH}/components/lwip/lwip/src/core/timeouts.c" lwip_original)
file(READ "${lwip_original}" lwip_code)
string(REPLACE "\r\n" "\n" lwip_code "${lwip_code}")
set(dhcp_block "#if LWIP_DHCP\n  {DHCP_COARSE_TIMER_MSECS, HANDLER(dhcp_coarse_tmr)},\n  {DHCP_FINE_TIMER_MSECS, HANDLER(dhcp_fine_tmr)},\n#endif")
string(FIND "${lwip_code}" "${dhcp_block}" block_offset)
string(REGEX MATCHALL "HANDLER\\(dhcp_fine_tmr\\)" fine_entries "${lwip_code}")
list(LENGTH fine_entries fine_count)
if(block_offset EQUAL -1 OR NOT fine_count EQUAL 1)
    message(FATAL_ERROR "SDK DHCP timer table differs; refusing the AP-only patch")
endif()
set(lwip_patched "${lwip_code}")
if(CONFIG_APP_DISABLE_DHCP_CLIENT_TIMERS)
    string(REPLACE "${dhcp_block}" "/* AP-only build: DHCP client cyclic timers disabled. */" lwip_patched "${lwip_patched}")
endif()

function(replace_lwip_part old new)
    string(FIND "${lwip_patched}" "${old}" part_offset)
    if(part_offset EQUAL -1)
        message(FATAL_ERROR "SDK timer implementation differs; refusing network pause patch")
    endif()
    string(REPLACE "${old}" "${new}" result "${lwip_patched}")
    set(lwip_patched "${result}" PARENT_SCOPE)
endfunction()

if(CONFIG_APP_PAUSE_NETWORK_TIMERS)
    replace_lwip_part("static u32_t current_timeout_due_time;"
        "static u32_t current_timeout_due_time;\nstatic int app_timers_paused;")
    replace_lwip_part("if (!tcpip_tcp_timer_active && (tcp_active_pcbs || tcp_tw_pcbs))"
        "if (!app_timers_paused && !tcpip_tcp_timer_active && (tcp_active_pcbs || tcp_tw_pcbs))")
    replace_lwip_part("  cyclic->handler();" "  if (app_timers_paused) return;\n  cyclic->handler();")
    set(pause_fragment "${CMAKE_CURRENT_LIST_DIR}/lwip_timers.inc")
    file(READ "${pause_fragment}" pause_code)
    string(REPLACE "\r\n" "\n" pause_code "${pause_code}")
    set(pause_marker "#else /* LWIP_TIMERS && !LWIP_TIMERS_CUSTOM */")
    replace_lwip_part("${pause_marker}" "${pause_code}\n${pause_marker}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${pause_fragment}")
    message(STATUS "AP-off: lwIP cyclic and TCP timers paused; restored before AP start")
endif()
set(lwip_generated "${CMAKE_BINARY_DIR}/lwip_timeouts.c")
file(WRITE "${lwip_generated}" "${lwip_patched}")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${lwip_original}")

idf_component_get_property(lwip_lib lwip COMPONENT_LIB)
get_target_property(lwip_sources ${lwip_lib} SOURCES)
list(FIND lwip_sources "${lwip_original}" source_index)
if(source_index EQUAL -1)
    message(FATAL_ERROR "SDK lwIP timeouts.c source missing; refusing the AP-only patch")
endif()
list(REMOVE_ITEM lwip_sources "${lwip_original}")
list(APPEND lwip_sources "${lwip_generated}")
set_property(TARGET ${lwip_lib} PROPERTY SOURCES "${lwip_sources}")
if(CONFIG_APP_DISABLE_DHCP_CLIENT_TIMERS)
    message(STATUS "AP-only A/B: DHCP client cyclic timers disabled; DHCP server retained")
endif()
